Feature unit tests
TaskarCenterAtUW/TDEI-node-ms-core pull request #24
Opened 2023-06-27 09:40 UTC by susrisha

- increases test coverage to 78%
- Added unit test cases for 
     - Topic
     - FileEntity
     - Queue
     - Storage Classes
     - Logger Classes
     - Configurations
     - Authorizer
NOTE: The enumeration document is not yet complete. Here are the test results from the above code:
```shell
> nodets-ms-core@0.0.8 test
> jest --silent

 PASS  test/local_logger.unit.ts
  Local logger
    ✓ Should initialize without parameters (1 ms)
    ✓ Should send add request (2 ms)
    ✓ Should be able to  update request
    ✓ Should be able to  add event
    ✓ Should be able to record metric
    ✓ Should record HTTP call
    ✓ Should send info (1 ms)
    ✓ Should send debug
    ✓ Should record message
    ✓ Should get Auditor

 PASS  test/queue.unit.ts
  Queue 
    ✓ Should get the Azure Queue (5 ms)
    ✓ Should be able to add messages (1 ms)
    ✓ Should be able to send messages
    ✓ Should call listen messages

 PASS  test/azure_storage_client.unit.ts
  Azure Storage Client
    ✓ Should initialize Client (1 ms)
    ✓ Should get Container with name
    ✓ Should get file from the container name and entity (1 ms)
    ✓ Should get file from URL

 PASS  test/topic.unit.ts
  Azure service bus topic
    ✓ Should have provider as azure (1 ms)
    ✓ Should get the service topic (1 ms)
    ✓ Should send message via ServiceBus when message is sent
    ✓ Should listen to the said subscription appropriately
    ✓ Should throw error when the client is not available (10 ms)
  Local topic
    ✓ Should have provider as Local (1 ms)
    ✓ Should get the service topic
    ✓ Should send message via ServiceBus when message is sent
    ✓ Should listen to the said subscription appropriately
    ✓ Should throw error when the client is not available (2 ms)

 PASS  test/azure_auditor.unit.ts
  Azure auditor
    ✓ Should initialize with queue name (1 ms)
    ✓ Should add event appropriately (1 ms)
    ✓ Should add request  (1 ms)
    ✓ Should update request 
    ✓ Should return object with empty queue also

 PASS  test/azure_storage_container.unit.ts
  Azure Storage container
    ✓ Should be able to initialize from ContainerClient (1 ms)
    ✓ Should be able to list files based on response from azure (1 ms)
    ✓ Should be able to create a file with given name (1 ms)

 PASS  test/azure_analytic.unit.ts
  Azure analytic
    ✓ Should initialize with queue name (1 ms)
    ✓ Should be able to send message (2 ms)

 PASS  test/local-topic.unit.ts
  Local topic unit test
    ✓ Should initialize with any config (12 ms)
    ✓ Should initialize without any config (1 ms)
    ✓ Should publish message to channel with publish (319 ms)
    ✓ Should consume from the channel with consume (303 ms)

 PASS  test/core.unit.ts
  Core unit tests
    ✓ Should initialize with default configuration (1 ms)
    ✓ Should initialize with Local Configuration (1 ms)
    ✓ Should get default storage client by default (8 ms)
    ✓ Should get Local storage client for local configuration
    ✓ Should get Local storage client for local Configuration
    ✓ Should get Azure storage client for azure config
    ✓ Should return Local storage client if core initialized by local and default storage requested (1 ms)
    ✓ Should get Azure logger by default
    ✓ Should return local logger for local
    ✓ Should return Hosted Authorizer if provider not given (3 ms)

 PASS  test/queue-message.unit.ts
  QueueMessage
    ✓ Should create Queue appropriately (5 ms)
    ✓ Should Instantiate

 PASS  test/logger.unit.ts
  Logger
    ✓ Should initialize with default configuration (11 ms)
    ✓ Should send info (1 ms)
    ✓ Should send debug
    ✓ Should send metric (1 ms)
    ✓ Should record HTTP call (8 ms)
    ✓ Should get auditor (5 ms)
    ✓ Should get analytic (4 ms)
    ✓ Should call send when sendAll called

 PASS  test/local_file_entity.unit.ts
  Local file entity
    ✓ Should get the file appropriately (1 ms)
    ✓ Should get the file from axios (30 ms)
    ✓ Should get the data text (2 ms)
    ✓ Should upload from data (1 ms)

 PASS  test/azure_file_entity.unit.ts
  Azure file entity
    ✓ Should be able to initialize
    ✓ Should be able to download when the file stream is needed
    ✓ Should be able to get the text (6 ms)
    ✓ Should be able to upload the content from readable stream (1 ms)

 PASS  test/azure-service-bus-topic.unit.ts
  Azure service bus topic unit
    ✓ Should initialize with Azure default config if not provided (1 ms)
    ✓ Should have called and created topic and sender on init
    ✓ Should listen to a subscription using subscribe method (1 ms)
    ✓ Should be able to call publish on sender when message is sent

 PASS  test/azure-service-bus-queue.unit.ts
  Azure service bus
    ✓ should intialize with proper queue (2 ms)
    ✓ Should be able to send messages (6 ms)
    ✓ Should be able to receive messages

 PASS  test/local_storage_container.unit.ts
  Local storage container
    ✓ Should be able to create with server root and name (1 ms)
    ✓ Should get list of files as given by server (1 ms)
    ✓ Should create a new file based on path

 PASS  test/core_config.unit.ts
  Core Configuration
    ✓ Should initialize Core default with Azure (2 ms)
    ✓ Should initialize Core default based on env variable

 PASS  test/local_storage_client.unit.ts
  Local storage client
    ✓ Should initialize Client appropriately (1 ms)
    ✓ Should return the container
    ✓ Should get file from container (1 ms)
    ✓ Should get the file from the URL
    ✓ Should throw a Not found error when not found (3 ms)

 PASS  test/azure_logger_config.unit.ts
  Azure logger Config
    ✓ Should have provider as azure (1 ms)
    ✓ Should pickup queuename from local configuration
    ✓ Should pickup queuename from parameter

 PASS  test/local_storage_config.unit.ts
  Local Storage config
    ✓ Should initialize with no configuration given
    ✓ Should take the env connection
    ✓ Should take values from default when default is called

 PASS  test/azure_storage_config.unit.ts
  Azure storage config
    ✓ Should initialize with given parameters (1 ms)
    ✓ Should get the value of connection string from process
    ✓ Default should pick up from env (1 ms)

 PASS  test/authorizer.int.ts (7.723 s)
  Authorizer (Hosted and Simulated)
    ✓ Should give HostedAuthorizer for configuration (2 ms)
    ✓ Should give SimulatedAuthorizer for configuration
    ✓ Should pick up host url from env if not given
    ✓ Should configure based on the url provided
    ✓ Should give error for no permissions (2 ms)
    ✓ Should give simulated result as false when userId is as per predefined
    ✓ Should give simulated result as expected (true)
    ✓ Should respond true when user has permission (1695 ms)
    ✓ Should respond false if user does not have permission (1237 ms)
    ✓ Should respond true if user has all the permissions required (1127 ms)
    ✓ Should reject if the URL is malformed (34 ms)

----------------------------------|---------|----------|---------|---------|-----------------------------------------------------------
File                              | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s                                         
----------------------------------|---------|----------|---------|---------|-----------------------------------------------------------
All files                         |   78.18 |    61.42 |   78.39 |   78.05 |                                                           
 src                              |   77.77 |    68.18 |     100 |   77.77 |                                                           
  core.ts                         |   77.77 |    68.18 |     100 |   77.77 | 30,41,60,76,96-97,105-111,121-122,152,163-168,186,197,204 
 src/core/auth/model              |     100 |      100 |     100 |     100 |                                                           
  auth_config.ts                  |     100 |      100 |     100 |     100 |                                                [...]

2023-06-27 10:21 UTC, MashB requested changes

2023-06-27 10:21 UTC, MashB commented on src/core.ts
> +            } else if(config.provider == 'Local'){
'Local' , if we can use CONST variable will help

2023-06-27 10:21 UTC, MashB commented on src/core/queue/providers/azure-service-bus-queue.ts
> +                console.log('Received message');
Remove console logs. sensitive messages will have concerns

2023-06-27 10:21 UTC, MashB commented on test-report.html
this file can be git ignored

2023-06-27 10:21 UTC, MashB commented on test/authorizer.int.ts
> +        const authorizer = Core.getAuthorizer({ provider: "Hosted" });
if we can use const enum for Provider will help. Applies to all such occurrences

2023-06-27 10:21 UTC, MashB commented on test/authorizer.int.ts
> +    it('Should respond true when user has permission', async () => {
for all Integration test create section (describe) or create file .integration.ts and move all tests

2023-06-27 14:31 UTC, MashB approved these changes

2023-06-28 06:05 UTC, sujata-m approved these changes

2023-06-29 04:06 UTC, merged