Fixed Task 1309
TaskarCenterAtUW/TDEI-node-ms-core pull request #36
Opened 2024-12-24 12:43 UTC by sujata-m

- Fixed Task [1309](https://dev.azure.com/TDEI-UW/TDEI/_workitems/edit/1309/)
- Added ability to subscribe number concurrent messages (configurable). If maxConcurrentMessages is not passed then it will process the messages according to the number of CPUs. 
    `Core.getTopic('topicName', configuration || null, maxConcurrentMessages=2)`
- Added ability to hold on acknowledgement until processing is completed
  - Added private processMessage function which will hold the acknowledgement until message is fully processed
- Updated unittest cases/

Test Code - 

```
import { Core } from "./core";
import { QueueMessage } from "./core/queue";
import { AzureQueueConfig } from "./core/queue/providers/azure-queue-config";
// Get the dotenv things
require("dotenv").config();

const topicConfig = new AzureQueueConfig();
topicConfig.connectionString = process.env.QUEUECONNECTION || "";
topicConfig.provider = process.env.PROVIDER || "";

const topicObject = Core.getTopic("temp-anuj", topicConfig, 2);

const publishMessages = async (nuOfMessages: number) => {
    for (let i = 1; i <= nuOfMessages; i++) {
        try {
            await topicObject.publish(
                QueueMessage.from({
                    message: `ID: ${i}`,
                    data: {
                        id: i,
                    },
                })
            );
            console.log(`Published message ${i}`);
        } catch (error) {
            console.error(`Failed to publish message ${i}:`, error);
        }
    }
};

async function processMessage(message: QueueMessage): Promise<void> {
    console.log("Received Message");
    console.log(message.toJSON());

    // Simulate actual processing (replace this with your logic)
    return new Promise((resolve) => {
        setTimeout(() => {
            console.log("Message processed successfully");
            resolve();
        }, 5 * 60 * 1000); // Example: Simulate 5 minutes of processing
    });
}

function processError(error: any) {
    console.error("Received error:", error);
}

const subscribeMessages = async () => {
    try {
        await topicObject.subscribe(
            "handle",
            {
                onReceive: processMessage,
                onError: processError,
            }
        );
        console.log("Message subscription Started");
    } catch (error) {
        console.error("Failed to subscribe to messages:", error);
    }
};

const main = async () => {

    // Publish messages
    await publishMessages(10);

    // Start subscription first
    await subscribeMessages();

};

main().catch((error) => {
    console.error("Error in main execution:", error);
});

```

2024-12-30 10:17 UTC, MashB commented
@sujata-m , Please add logic for auto renewal of message.

2024-12-30 10:17 UTC, MashB requested changes
@sujata-m , Please add logic for auto renewal of message.

2025-01-02 09:24 UTC, susrisha commented on src/core/queue/providers/azure-service-bus-topic.ts
> +        }, 30000); // Renew lock every 30 seconds
hardcoded number. Either put up a constant or make it configurable

2025-01-02 09:26 UTC, sujata-m commented on src/core/queue/providers/azure-service-bus-topic.ts
> +        }, 30000); // Renew lock every 30 seconds
okay

2025-01-02 10:45 UTC, susrisha approved these changes

2025-01-02 16:06 UTC, MashB approved these changes

2025-01-06 05:35 UTC, merged